# Generated by Django 5.2.14 on 2026-05-30 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_source', '0001_initial'),
        ('tv_channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockContainerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('planned_item_count', models.PositiveIntegerField(default=1)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'started'), (2, 'paused'), (3, 'completed'), (4, 'cancelled'), (5, 'skipped')], default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_channel.gridblock')),
                ('last_scheduled_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_source.mediaitem')),
                ('media_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_source.mediacontainer')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleMediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_to_playout', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('post_roll_filler_ends_at', models.DateTimeField(blank=True, null=True)),
                ('block_container_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid_schedule.blockcontainerselection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_source.mediaitem')),
            ],
        ),
        migrations.CreateModel(
            name='TvPlayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv_channel.gridlayout')),
                ('tv_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_channel.tvchannel')),
            ],
        ),
        migrations.AddField(
            model_name='blockcontainerselection',
            name='tv_playout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid_schedule.tvplayout'),
        ),
        migrations.AddConstraint(
            model_name='tvplayout',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tv_channel',), name='unique_active_playout_per_channel'),
        ),
        migrations.AlterUniqueTogether(
            name='blockcontainerselection',
            unique_together={('tv_playout', 'block', 'order')},
        ),
    ]
