# Generated by Django 5.2.14 on 2026-05-31 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_schedule', '0001_initial'),
        ('tv_channel', '0003_alter_catalog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvplayout',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_channel.gridlayout'),
        ),
    ]
