# Generated by Django 5.2.15 on 2026-07-06 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_schedule', '0003_alter_schedulemediaitem_block_container_selection_and_more'),
        ('media_source', '0004_mediacontainer_provider_ids'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedulemediaitem',
            name='schedule_item_has_exactly_one_selection',
        ),
        migrations.AddField(
            model_name='schedulemediaitem',
            name='parent_schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_roll_items', to='grid_schedule.schedulemediaitem'),
        ),
        migrations.AddField(
            model_name='schedulemediaitem',
            name='role',
            field=models.IntegerField(choices=[(1, 'main'), (2, 'trailer'), (3, 'promo'), (4, 'ad'), (5, 'bumper'), (6, 'ident'), (7, 'filler'), (8, 'psa'), (99, 'other')], default=1),
        ),
        migrations.AddConstraint(
            model_name='schedulemediaitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('block_container_selection__isnull', False), ('flexible_selection__isnull', True), ('parent_schedule_item__isnull', True), ('role', 1)), models.Q(('block_container_selection__isnull', True), ('flexible_selection__isnull', False), ('parent_schedule_item__isnull', True), ('role', 1)), models.Q(models.Q(('role', 1), _negated=True), ('block_container_selection__isnull', True), ('flexible_selection__isnull', True), ('parent_schedule_item__isnull', False)), _connector='OR'), name='schedule_item_selection_matches_role'),
        ),
    ]
