# Generated by Django 5.2.15 on 2026-07-06 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_schedule', '0004_remove_schedulemediaitem_schedule_item_has_exactly_one_selection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoutGenerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(choices=[('generate', 'generate'), ('extend', 'extend')], default='generate', max_length=16)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('generated_items', models.PositiveIntegerField(default=0)),
                ('filled_items', models.PositiveIntegerField(default=0)),
                ('repaired_gaps', models.PositiveIntegerField(default=0)),
                ('trimmed_overlaps', models.PositiveIntegerField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('tv_playout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_reports', to='grid_schedule.tvplayout')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
