# Generated by Django 5.2.15 on 2026-07-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_source', '0002_mediacontainer_actors_and_more'),
        ('tv_channel', '0004_gridlayout_mode_gridlayout_post_filler_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialFlowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'IDLE'), (1, 'ANALYZING'), (2, 'COMPLETE'), (3, 'SKIPPED'), (4, 'COMPLETE_WITH_ERRORS'), (5, 'CANCELLED')], default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('algorithm_version', models.CharField(default='1.0', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('model_state', models.JSONField(blank=True, default=dict)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('source_media_count', models.PositiveIntegerField(default=0)),
                ('segment_count', models.PositiveIntegerField(default=0)),
                ('channel_candidate_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_flow_runs', to='tv_channel.catalog')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EditorialChannelCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('viability_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('viable', 'viable'), ('weak', 'weak'), ('rejected', 'rejected'), ('selected', 'selected'), ('published', 'published')], default='viable', max_length=32)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tv_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_channel_candidates', to='tv_channel.tvchannel')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_candidates', to='editorial_planning.editorialflowrun')),
            ],
            options={
                'ordering': ('-viability_score', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EditorialSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('reference_vector', models.JSONField(blank=True, default=list)),
                ('reference_profile', models.JSONField(blank=True, default=dict)),
                ('observed_profile', models.JSONField(blank=True, default=dict)),
                ('programmable_score', models.FloatField(default=0.0)),
                ('cohesion_score', models.FloatField(default=0.0)),
                ('separation_score', models.FloatField(default=0.0)),
                ('format_consistency_score', models.FloatField(default=0.0)),
                ('volume_score', models.FloatField(default=0.0)),
                ('labelability_score', models.FloatField(default=0.0)),
                ('acceptance_threshold', models.FloatField(default=0.0)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='editorial_planning.editorialflowrun')),
            ],
            options={
                'ordering': ('-programmable_score', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EditorialChannelSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('anchor', 'anchor'), ('support', 'support'), ('secondary', 'secondary')], default='secondary', max_length=32)),
                ('weight', models.FloatField(default=0.0)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('channel_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_segments', to='editorial_planning.editorialchannelcandidate')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_segments', to='editorial_planning.editorialsegment')),
            ],
            options={
                'ordering': ('position', '-weight', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EditorialSegmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('is_primary', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('secondary', 'secondary'), ('ambiguous', 'ambiguous'), ('rejected', 'rejected'), ('pending', 'pending'), ('manual_override', 'manual_override')], default='accepted', max_length=32)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_segment_memberships', to='media_source.mediacontainer')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='editorial_planning.editorialsegment')),
            ],
            options={
                'ordering': ('segment', '-score', 'media_container'),
            },
        ),
        migrations.CreateModel(
            name='EditorialSegmentPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loop', models.BooleanField(default=True)),
                ('global_score', models.FloatField(default=0.0)),
                ('transition_scores', models.JSONField(blank=True, default=dict)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segment_path', to='editorial_planning.editorialchannelcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='EditorialSegmentPathElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('anchor', 'anchor'), ('support', 'support'), ('secondary', 'secondary')], default='secondary', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('transition_from_previous_score', models.FloatField(default=0.0)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='editorial_planning.editorialsegmentpath')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_elements', to='editorial_planning.editorialsegment')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='editorialflowrun',
            index=models.Index(fields=['catalog', 'is_active'], name='editorial_p_catalog_58815b_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialchannelcandidate',
            index=models.Index(fields=['run', 'status'], name='editorial_p_run_id_cd31a3_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialchannelcandidate',
            index=models.Index(fields=['tv_channel', 'status'], name='editorial_p_tv_chan_f5afc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialchannelcandidate',
            constraint=models.UniqueConstraint(fields=('run', 'channel_key'), name='unique_editorial_channel_key_per_run'),
        ),
        migrations.AddIndex(
            model_name='editorialsegment',
            index=models.Index(fields=['run', 'segment_key'], name='editorial_p_run_id_f1f584_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialsegment',
            constraint=models.UniqueConstraint(fields=('run', 'segment_key'), name='unique_editorial_segment_key_per_run'),
        ),
        migrations.AddIndex(
            model_name='editorialchannelsegment',
            index=models.Index(fields=['channel_candidate', 'role'], name='editorial_p_channel_ba487a_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialchannelsegment',
            constraint=models.UniqueConstraint(fields=('channel_candidate', 'segment'), name='unique_editorial_channel_segment'),
        ),
        migrations.AddIndex(
            model_name='editorialsegmentmembership',
            index=models.Index(fields=['media_container', 'status'], name='editorial_p_media_c_34a962_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialsegmentmembership',
            constraint=models.UniqueConstraint(fields=('segment', 'media_container'), name='unique_editorial_segment_membership'),
        ),
        migrations.AddConstraint(
            model_name='editorialsegmentpathelement',
            constraint=models.UniqueConstraint(fields=('path', 'position'), name='unique_editorial_segment_path_position'),
        ),
    ]
