# Generated by Django 5.2.15 on 2026-07-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_planning', '0001_initial'),
        ('tv_channel', '0004_gridlayout_mode_gridlayout_post_filler_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialPlannedGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planned_grid', to='editorial_planning.editorialchannelcandidate')),
                ('grid_layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_planning_source', to='tv_channel.gridlayout')),
            ],
        ),
    ]
