# Generated by Django 5.2.15 on 2026-07-16 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CategoryNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.IntegerField(choices=[(1, 'fiction'), (2, 'documentary'), (3, 'music'), (4, 'sport'), (5, 'news'), (6, 'show'), (99, 'other')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nature_links', to='rule_engine.category')),
            ],
            options={
                'unique_together': {('category', 'nature')},
            },
        ),
    ]
