# Generated by Django 5.2.16 on 2026-07-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0002_alter_category_category_categorynature'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['axis', 'value'], name='rule_engine_axis_9ac696_idx')],
                'constraints': [models.UniqueConstraint(fields=('axis', 'value'), name='unique_vocabulary_axis_value')],
            },
        ),
    ]
