# Generated by Django 5.2.14 on 2026-05-30 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillerPolicyPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name='GridLayoutPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GridBlockPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('priority', models.PositiveIntegerField(default=50)),
                ('min_items', models.PositiveIntegerField(default=1)),
                ('max_items', models.PositiveIntegerField(default=1)),
                ('min_duration_seconds_per_item', models.PositiveIntegerField(blank=True, null=True)),
                ('max_duration_seconds_per_item', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_categories', models.JSONField(default=list)),
                ('forbidden_categories', models.JSONField(default=list)),
                ('preferred_categories', models.JSONField(default=list)),
                ('allowed_natures', models.JSONField(default=list)),
                ('forbidden_natures', models.JSONField(default=list)),
                ('preferred_natures', models.JSONField(default=list)),
                ('allowed_container_kinds', models.JSONField(default=list)),
                ('forbidden_container_kinds', models.JSONField(default=list)),
                ('preferred_container_kinds', models.JSONField(default=list)),
                ('required_fields', models.JSONField(default=list)),
                ('post_filler_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid_layout_preset.fillerpolicypreset')),
                ('grid_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid_layout_preset.gridlayoutpreset')),
            ],
        ),
    ]
