# Generated by Django 5.2.14 on 2026-05-30 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analyze_status', models.IntegerField(choices=[(0, 'IDLE'), (1, 'ANALYZING'), (2, 'COMPLETE'), (3, 'SKIPPED'), (4, 'COMPLETE_WITH_ERRORS'), (5, 'CANCELLED')], default=0)),
                ('programming_role', models.IntegerField(blank=True, choices=[(1, 'main'), (2, 'trailer'), (3, 'promo'), (4, 'ad'), (5, 'bumper'), (6, 'ident'), (7, 'filler'), (8, 'psa'), (99, 'other')], null=True)),
                ('nature', models.IntegerField(blank=True, choices=[(1, 'fiction'), (2, 'documentary'), (3, 'music'), (4, 'sport'), (5, 'news'), (6, 'show'), (99, 'other')], null=True)),
                ('hash_data', models.TextField()),
                ('container_kind', models.IntegerField(blank=True, choices=[(1, 'standalone_video'), (2, 'series'), (3, 'music_release'), (4, 'music_video_release'), (99, 'other')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('credentials', models.JSONField(default=dict)),
                ('source_type', models.IntegerField(default=1)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analyze_status', models.IntegerField(choices=[(0, 'IDLE'), (1, 'ANALYZING'), (2, 'COMPLETE'), (3, 'SKIPPED'), (4, 'COMPLETE_WITH_ERRORS'), (5, 'CANCELLED')], default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MediaContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_data_hash', models.TextField()),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analyze_status', models.IntegerField(choices=[(0, 'IDLE'), (1, 'ANALYZING'), (2, 'COMPLETE'), (3, 'SKIPPED'), (4, 'COMPLETE_WITH_ERRORS'), (5, 'CANCELLED')], default=0)),
                ('categories', models.JSONField(default=list)),
                ('item_count', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_min_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_max_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('total_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('min_video_width', models.PositiveIntegerField(blank=True, null=True)),
                ('min_video_height', models.PositiveIntegerField(blank=True, null=True)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('countries', models.JSONField(default=list)),
                ('audio_languages', models.JSONField(default=list)),
                ('subtitle_languages', models.JSONField(default=list)),
                ('audio_languages_any', models.JSONField(default=list)),
                ('subtitle_languages_any', models.JSONField(default=list)),
                ('overall_rating_score', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('genres', models.JSONField(default=list)),
                ('raw_data', models.JSONField(default=dict)),
                ('is_missing', models.BooleanField(default=False)),
                ('media_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_source.mediacollection')),
                ('media_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_source.mediasource')),
            ],
            options={
                'unique_together': {('external_id', 'media_source')},
            },
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='media_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_source.mediasource'),
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_data_hash', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sequence_number', models.PositiveIntegerField(blank=True, null=True)),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('countries', models.JSONField(default=list)),
                ('audio_languages', models.JSONField(default=list)),
                ('subtitle_languages', models.JSONField(default=list)),
                ('video_width', models.PositiveIntegerField(blank=True, null=True)),
                ('video_height', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_rating_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analyze_status', models.IntegerField(choices=[(0, 'IDLE'), (1, 'ANALYZING'), (2, 'COMPLETE'), (3, 'SKIPPED'), (4, 'COMPLETE_WITH_ERRORS'), (5, 'CANCELLED')], default=0)),
                ('external_id', models.CharField(max_length=255)),
                ('is_missing', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(default=dict)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='media_source.mediacontainer')),
                ('media_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_source.mediasource')),
            ],
            options={
                'unique_together': {('external_id', 'media_source')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='mediacollection',
            unique_together={('external_id', 'media_source')},
        ),
    ]
