# Generated by Django 5.2.14 on 2026-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontainer',
            name='actors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='community_rating_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='creators',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='critic_rating_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='directors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='people',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='release_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='release_date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='release_year_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='release_year_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='studios',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediacontainer',
            name='writers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='actors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='community_rating_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='creators',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='critic_rating_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='directors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='genres',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='item_kind',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='people',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='studios',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='writers',
            field=models.JSONField(default=list),
        ),
    ]
