# Generated by Django 5.2.15 on 2026-07-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_source', '0002_mediacontainer_actors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacollection',
            name='is_anime',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
