# Generated by Django 5.2.15 on 2026-07-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_source', '0003_mediacollection_is_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontainer',
            name='provider_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
