# Generated by Django 5.2.14 on 2026-05-30 11:30

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('analyze_status', models.IntegerField(choices=[(0, 'IDLE'), (1, 'ANALYZING'), (2, 'COMPLETE'), (3, 'SKIPPED'), (4, 'COMPLETE_WITH_ERRORS'), (5, 'CANCELLED')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FillerPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('duration_seconds', models.PositiveIntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name='GridLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GridBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('priority', models.PositiveIntegerField(default=50)),
                ('min_items', models.PositiveIntegerField(default=1)),
                ('max_items', models.PositiveIntegerField(default=1)),
                ('min_duration_seconds_per_item', models.PositiveIntegerField(blank=True, null=True)),
                ('max_duration_seconds_per_item', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_categories', models.JSONField(default=list)),
                ('forbidden_categories', models.JSONField(default=list)),
                ('preferred_categories', models.JSONField(default=list)),
                ('allowed_natures', models.JSONField(default=list)),
                ('forbidden_natures', models.JSONField(default=list)),
                ('preferred_natures', models.JSONField(default=list)),
                ('allowed_container_kinds', models.JSONField(default=list)),
                ('forbidden_container_kinds', models.JSONField(default=list)),
                ('preferred_container_kinds', models.JSONField(default=list)),
                ('post_filler_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv_channel.fillerpolicy')),
                ('grid_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_channel.gridlayout')),
            ],
        ),
        migrations.CreateModel(
            name='TvChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specification', models.TextField(blank=True, help_text='Technical description of the channel. More detailled', null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='data/logos/')),
                ('external_playout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('analyze_status', models.CharField(choices=[(0, 'IDLE'), (1, 'ANALYZING'), (2, 'COMPLETE'), (3, 'SKIPPED'), (4, 'COMPLETE_WITH_ERRORS'), (5, 'CANCELLED')], default=0, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_channel.catalog')),
            ],
        ),
        migrations.AddField(
            model_name='gridlayout',
            name='tv_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_channel.tvchannel'),
        ),
        migrations.CreateModel(
            name='EditorialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_categories', models.JSONField(blank=True, default=list)),
                ('forbidden_categories', models.JSONField(blank=True, default=list)),
                ('preferred_categories', models.JSONField(blank=True, default=list)),
                ('allowed_natures', models.JSONField(blank=True, default=list)),
                ('forbidden_natures', models.JSONField(blank=True, default=list)),
                ('preferred_natures', models.JSONField(blank=True, default=list)),
                ('allowed_container_kinds', models.JSONField(blank=True, default=list)),
                ('forbidden_container_kinds', models.JSONField(blank=True, default=list)),
                ('preferred_container_kinds', models.JSONField(blank=True, default=list)),
                ('start_at', models.TimeField(default=datetime.time(6, 0))),
                ('end_at', models.TimeField(default=datetime.time(22, 0))),
                ('allow_filler', models.BooleanField(default=True)),
                ('tv_channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tv_channel.tvchannel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gridlayout',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tv_channel',), name='unique_active_grid_layout_per_channel'),
        ),
    ]
