# Generated by Django 5.2.14 on 2026-05-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='number_of_channels',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
