# Generated by Django 5.2.14 on 2026-05-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_channel', '0002_catalog_number_of_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
