# Generated by Django 5.2.15 on 2026-07-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_channel', '0003_alter_catalog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridlayout',
            name='mode',
            field=models.IntegerField(choices=[(1, 'fixed'), (2, 'flexible')], default=1),
        ),
        migrations.AddField(
            model_name='gridlayout',
            name='post_filler_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv_channel.fillerpolicy'),
        ),
    ]
