# Generated by Django 5.2.15 on 2026-07-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_channel', '0004_gridlayout_mode_gridlayout_post_filler_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillerpolicy',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
