# Generated by Django 5.2.15 on 2026-07-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_channel', '0005_fillerpolicy_allowed_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialline',
            name='allowed_categories',
        ),
        migrations.RemoveField(
            model_name='editorialline',
            name='allowed_container_kinds',
        ),
        migrations.RemoveField(
            model_name='editorialline',
            name='allowed_natures',
        ),
        migrations.RemoveField(
            model_name='editorialline',
            name='forbidden_categories',
        ),
        migrations.RemoveField(
            model_name='editorialline',
            name='forbidden_container_kinds',
        ),
        migrations.RemoveField(
            model_name='editorialline',
            name='forbidden_natures',
        ),
        migrations.RemoveField(
            model_name='editorialline',
            name='preferred_categories',
        ),
        migrations.RemoveField(
            model_name='editorialline',
            name='preferred_container_kinds',
        ),
        migrations.RemoveField(
            model_name='editorialline',
            name='preferred_natures',
        ),
        migrations.RemoveField(
            model_name='gridblock',
            name='allowed_categories',
        ),
        migrations.RemoveField(
            model_name='gridblock',
            name='allowed_container_kinds',
        ),
        migrations.RemoveField(
            model_name='gridblock',
            name='allowed_natures',
        ),
        migrations.RemoveField(
            model_name='gridblock',
            name='forbidden_categories',
        ),
        migrations.RemoveField(
            model_name='gridblock',
            name='forbidden_container_kinds',
        ),
        migrations.RemoveField(
            model_name='gridblock',
            name='forbidden_natures',
        ),
        migrations.RemoveField(
            model_name='gridblock',
            name='preferred_categories',
        ),
        migrations.RemoveField(
            model_name='gridblock',
            name='preferred_container_kinds',
        ),
        migrations.RemoveField(
            model_name='gridblock',
            name='preferred_natures',
        ),
        migrations.AddField(
            model_name='editorialline',
            name='allowed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='editorialline',
            name='forbidden',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='editorialline',
            name='preferred',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gridblock',
            name='allowed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gridblock',
            name='forbidden',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gridblock',
            name='preferred',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
