# Generated by Django 5.2.15 on 2026-07-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_channel', '0006_remove_editorialline_allowed_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvchannel',
            name='programming_mode',
            field=models.IntegerField(choices=[(1, 'classic'), (2, 'marathon')], default=1),
        ),
        migrations.AlterField(
            model_name='gridlayout',
            name='mode',
            field=models.IntegerField(choices=[(1, 'fixed'), (2, 'flexible'), (3, 'marathon')], default=1),
        ),
        migrations.CreateModel(
            name='MarathonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grid_layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_config', to='tv_channel.gridlayout')),
            ],
        ),
        migrations.CreateModel(
            name='MarathonKindPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_kind', models.IntegerField(choices=[(1, 'standalone_video'), (2, 'series'), (3, 'music_release'), (4, 'music_video_release'), (99, 'other')])),
                ('min_run', models.PositiveIntegerField(default=1)),
                ('max_run', models.PositiveIntegerField(default=1)),
                ('quota', models.PositiveIntegerField(default=1)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kind_policies', to='tv_channel.marathonconfig')),
            ],
            options={
                'ordering': ('container_kind', 'id'),
                'constraints': [models.UniqueConstraint(fields=('config', 'container_kind'), name='unique_marathon_kind_policy_per_config')],
            },
        ),
    ]
