# Generated by Django 5.2.15 on 2026-07-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_channel', '0007_tvchannel_programming_mode_alter_gridlayout_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelImageSuggestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'logo')], default=1)),
                ('status', models.IntegerField(choices=[(0, 'IDLE'), (1, 'ANALYZING'), (2, 'COMPLETE'), (3, 'SKIPPED'), (4, 'COMPLETE_WITH_ERRORS'), (5, 'CANCELLED')], default=0)),
                ('entity_type', models.CharField(blank=True, choices=[('studio', 'studio'), ('person', 'person'), ('theme', 'theme')], max_length=16)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('query_source', models.CharField(blank=True, choices=[('axes', 'axes'), ('llm', 'llm'), ('user', 'user')], max_length=16)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tv_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_suggestion_runs', to='tv_channel.tvchannel')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChannelImageSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('provider', models.CharField(max_length=16)),
                ('source_url', models.URLField(max_length=1000)),
                ('thumbnail', models.FileField(upload_to='data/image_suggestions/')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('attribution', models.CharField(blank=True, max_length=255)),
                ('is_chosen', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='tv_channel.channelimagesuggestionrun')),
            ],
            options={
                'ordering': ('run', 'position'),
            },
        ),
        migrations.AddIndex(
            model_name='channelimagesuggestionrun',
            index=models.Index(fields=['tv_channel', '-created_at'], name='tv_channel__tv_chan_dd971f_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelimagesuggestion',
            constraint=models.UniqueConstraint(fields=('run', 'position'), name='unique_channel_image_suggestion_position'),
        ),
    ]
