import {Component, Inject} from '@angular/core';
import {FormGroup, ReactiveFormsModule} from '@angular/forms';
import {NgIf} from '@angular/common';
import {MAT_DIALOG_DATA, MatDialogModule, MatDialogRef} from '@angular/material/dialog';
import {MatButtonModule} from '@angular/material/button'; import {MatProgressSpinnerModule} from '@angular/material/progress-spinner';
import {FormlyFieldConfig, FormlyModule} from '@ngx-formly/core';
import {FormOptions, FormSuggestionResponse, GridBlock, GridBlockPayload} from '@project-interfaces/tv-channel';
import {GridBlockService} from '@project-services/grid-block.service'; import {TvChannelService} from '@project-services/tv-channel.service';
import {DialogContainer1Component} from '@project-templates/dialog-container1/dialog-container1.component'; import {SuggestionPanelComponent} from '@project-templates/suggestion-panel/suggestion-panel.component';
@Component({selector:'app-grid-block-edit-dialog',standalone:true,imports:[ReactiveFormsModule,NgIf,MatDialogModule,MatButtonModule,MatProgressSpinnerModule,FormlyModule,DialogContainer1Component,SuggestionPanelComponent],templateUrl:'./grid-block-edit-dialog.component.html',styleUrl:'./grid-block-edit-dialog.component.css'})
export class GridBlockEditDialogComponent {
 form=new FormGroup({});model:GridBlockPayload;fields:FormlyFieldConfig[];isSubmitting=false;isSuggesting=false;error:string|null=null
 constructor(private blocks:GridBlockService,private channels:TvChannelService,private ref:MatDialogRef<GridBlockEditDialogComponent>,@Inject(MAT_DIALOG_DATA) public data:{channelId:string|number,gridLayoutId:string|number,block:GridBlock|null,formOptions:FormOptions}){
  this.model={...this.empty(),...(data.block??{}),grid_layout:data.gridLayoutId}; const multi=(key:string,label:string,options:any[]):FormlyFieldConfig=>({key,type:'select',props:{label,multiple:true,options}});const cats=data.formOptions.categories.map(value=>({label:value,value}));
  this.fields=[{fieldGroupClassName:'compact-row',fieldGroup:[{key:'starts_at',type:'input',props:{label:'Début',type:'time',required:true}},{key:'ends_at',type:'input',props:{label:'Fin',type:'time',required:true}},{key:'priority',type:'input',props:{label:'Priorité',type:'number',min:0,max:100,required:true}}]},
   {fieldGroupClassName:'compact-row',fieldGroup:[{key:'min_items',type:'input',props:{label:'Minimum éléments',type:'number',min:1,max:3,required:true}},{key:'max_items',type:'input',props:{label:'Maximum éléments',type:'number',min:1,max:3,required:true}},{key:'min_duration_seconds_per_item',type:'input',props:{label:'Durée minimum (s)',type:'number',min:1}},{key:'max_duration_seconds_per_item',type:'input',props:{label:'Durée maximum (s)',type:'number',min:1}}]},
   multi('allowed_categories','Catégories autorisées',cats),multi('forbidden_categories','Catégories interdites',cats),multi('preferred_categories','Catégories préférées',cats),multi('allowed_natures','Natures autorisées',data.formOptions.natures),multi('forbidden_natures','Natures interdites',data.formOptions.natures),multi('preferred_natures','Natures préférées',data.formOptions.natures),multi('allowed_container_kinds','Types autorisés',data.formOptions.container_kinds),multi('forbidden_container_kinds','Types interdits',data.formOptions.container_kinds),multi('preferred_container_kinds','Types préférés',data.formOptions.container_kinds),
   {key:'post_filler_policy',type:'select',props:{label:'Politique post-remplissage',options:[{label:'Aucune',value:null},...data.formOptions.filler_policies.map(x=>({label:`${x.name} (${x.duration_seconds}s)`,value:x.id}))]}}]
 }
 suggest(context:string){this.isSuggesting=true;this.error=null;const {grid_layout,...values}=this.model;this.channels.suggestForm(this.data.channelId,{form_kind:'grid_block',user_context:context,current_values:values,...(this.data.block?{grid_block_id:this.data.block.id}:{})}).subscribe(r=>{this.isSuggesting=false;if(!r.isOk){this.error=this.detail(r.body);return}const v=(r.body as FormSuggestionResponse).values;Object.assign(this.model,v);this.form.patchValue(v)})}
 save(){if(this.form.invalid||this.isSubmitting){this.form.markAllAsTouched();return}this.isSubmitting=true;this.error=null;const request=this.data.block?this.blocks.update(this.data.block.id,this.model):this.blocks.create(this.model);request.subscribe(r=>{this.isSubmitting=false;if(!r.isOk){this.error=this.detail(r.body);return}this.ref.close({saved:true})})}
 private detail(v:any){return v?.error?.detail??(v?.error?JSON.stringify(v.error):'Enregistrement impossible.')}
 private empty():GridBlockPayload{return {grid_layout:this.data?.gridLayoutId??'',starts_at:'12:00',ends_at:'13:00',priority:50,min_items:1,max_items:1,min_duration_seconds_per_item:null,max_duration_seconds_per_item:null,allowed_categories:[],forbidden_categories:[],preferred_categories:[],allowed_natures:[],forbidden_natures:[],preferred_natures:[],allowed_container_kinds:[],forbidden_container_kinds:[],preferred_container_kinds:[],post_filler_policy:null}}
}
